ops-have-all-perms: false

groups:
  default:
    default: true
    can-pick-up-items: true
    permissions: 
      
  admin: 
    default: false
    can-pick-up-items: true
    prefix: 
    permissions:
      - ultraperms.main
      - ultraperms.add
      - ultraperms.remove
      
players:
  uuid:
    group: default
    prefix: 
    
    
      